### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by drkthunder02** [bahrmichael/brave-bucks#50]
Is there a way to install this for other organizations to utilize?  If so what dependencies on a linux system are needed?

**Comment by bahrmichael** [comment]
Yup, you need a couple tools to build:
- JDK for Java 8
- Maven
- NPM
- Angular

To run it, you need a MongoDB and a server with JRE for Java 8.

Check https://github.com/bahrmichael/brave-bucks/blob/master/src/main/resources/config/application-dev.yml for parameter config, you can ignore the monitoring bits.

For MongoDB you need to create a couple tables as shown in https://github.com/bahrmichael/brave-bucks/tree/master/src/main/java/com/bravebucks/eve/repository

**Comment by drkthunder02** [comment]
Any particular version of Maven?  The latest version of Maven utilizes JDK for Java 11, and not 8.

**Comment by drkthunder02** [comment]
What is the entry point for Java for use with apache2?

**Comment by drkthunder02** [comment]
Can't get past this error:

2020-06-10 09:28:50.383  WARN 28409 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'walletParser': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'WALLET_CLIENT_ID' in value "${WALLET_CLIENT_ID}"
2020-06-10 09:28:50.423 ERROR 28409 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'walletParser': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'WALLET_CLIENT_ID' in value "${WALLET_CLIENT_ID}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at com.bravebucks.eve.BraveBucksApp.main(BraveBucksApp.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'WALLET_CLIENT_ID' in value "${WALLET_CLIENT_ID}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:831)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1086)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)

**Comment by bahrmichael** [comment]
> What is the entry point for Java for use with apache2?

The app was built with JHipster which again uses SpringBoot. No entry point for apache2 probably, but you should be able to use `mvn spring-boot:run`.

**Comment by bahrmichael** [comment]
`WALLET_CLIENT_ID` is required if your app shall also track ratting of your corp members (if you want to let them boost ADMs and pay them for ratting there. Fill them with blank or jibberish if you don't want to support that tracker. Create an esi app which requires the user to grant `esi-wallet.read_character_wallet.v1` and pass in the id and secret as `WALLET_CLIENT_ID` and `WALLET_CLIENT_SECRET ` as environment variables. See https://github.com/bahrmichael/brave-bucks/blob/master/src/main/java/com/bravebucks/eve/service/WalletParser.java and https://github.com/bahrmichael/brave-bucks/blob/master/src/main/webapp/app/home/wallet-tracker-info/wallet-tracker-info.component.html for more details.
